### ISSUE TITLE
Craft heads Bug

### ISSUE THREAD

**Issue by Hardko** [Thatsmusic99/HeadsPlus#19] opened 2018-12-25 20:43 UTC
### Short summary of issue
Hi, first, Merry christmas! and second... I found a bug when I try to craft heads, I use a skeleton head by default, but if this is a head of headsplus doesn't recognize and the plugin generate NBT Tag in other items.
### Server version
Spigot 1.13.2
### HeadsPlus version
Latest (5.3 and 5.2.10)
### Detailed description (how you found it, what you were doing at the time)
When I was looking for an error regarding the NBT Tag in my server, I thought it was caused by this plugin and that's how it was, this plugin trigger NBT Tags in randoms items when I craft and not minus important the crafting heads doesn't work correctly, I try change the base item for a Wither Skeleton Head, I don't use the head in the plugin, but when I go to craft, this have a NBT Tag and can't craft a head.
I try it in a Online Server and Offline Server and I have the same result,
### Expected behaviour
Correctly crafting heads with skeleton head from HeadsPlus and see why generate NBT Tag on random items or craftings.
### Actual behaviour
Can't craft heads with heads of Headsplus or other item base. Random items have a NBT Tag randomly.
### Steps to reproduce
Heads crafting:
-Take a one head of Skeleton (HeadsPlus) from loot and one of creative.
-Try to craft a Zombie head for example.

NBT Tag (example: wither skeleton head) :
-Take a Wither Skeleton Head clean from creative or command.
-Put the head in a crafting table, he has now a NBT Tag.

### Any last notes?
With randomly items crafting I try to reproduce, but I can't in the "clean" server, maybe is other plugin with HeadsPlus what causes this.

**Comment by Thatsmusic99** [comment] 2018-12-25 20:48
Hi,

Thanks for the bug report. I have heard a few things about NBT tags here and there however HeadsPlus uses them to store the head types created, whether they can be sold or not, and so on. However crafting heads is something I don't always like venturing into unless I desperately have to, like now. Will say if I can reproduce any of the issues or not.

Again thank you, and Merry Christmas to you too!~

**Comment by Thatsmusic99** [comment] 2018-12-25 20:59
Can't reproduce the heads crafting issue. Can you show me your heads.yml for this?

**Comment by Hardko** [comment] 2018-12-25 21:06
Sure :)

Here are my 2 configurations, the "clean version" and "official server version".
https://gist.github.com/Hardko/88a500220762615f1af525f0b5552547

**Comment by Thatsmusic99** [comment] 2018-12-26 07:07
Aha, I see why:

    skeleton:
        name:
        - MHF_Skeleton

Change MHF_Skeleton to {mob-default} which will make skeletons drop ordinary skeleton skulls and let you craft with them, or at least that's what I did.

I can't seem to get anything in terms of there being random items being given NBT tags. However I will try and add a new debug option to see what NBT tags are stored in an item.

**Comment by Thatsmusic99** [comment] 2018-12-26 07:57
Try using /hp debug item whilst holding one of the randomly tagged items using this version: https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v5.3.1-SNAPSHOT

**Comment by Hardko** [comment] 2018-12-26 19:19
I use the command with some items, the last debug is from "clean" item.
Here is the items debug:
https://gist.github.com/Hardko/e108a03d5d016c664790cf89092b7401

**Comment by Thatsmusic99** [comment] 2018-12-26 19:35
"NBT Tags": {
        "headsplus-sell": "1b",
        "headsplus-type": "\"\""
      },
      "amount": 0,
     "material": "AIR"

Somehow the plugin gave air NBT tags. I mean... wow.

Will take a look into that now. Thank you!

**Comment by Thatsmusic99** [comment] 2018-12-26 19:58
Reproduced successfully.

**Comment by Thatsmusic99** [comment] 2018-12-26 20:47
Should be fixed here: https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v5.3.1-SNAPSHOT-2

**Comment by Hardko** [comment] 2018-12-27 16:46
I can't reproduce the bug again, I think the NBT Tag it's fixed and the same thing with crafting.
Thanks!

**Closed** 2018-12-31 15:52 UTC
