### ISSUE TITLE
Error in console about crafting.

### ISSUE THREAD

**Issue by kaimokene** [Thatsmusic99/HeadsPlus#11] opened 2018-10-18 11:56 UTC
Theres just a error in console. It seems that theres something with the crafting we do have
    craft-heads disabled if that matters.
https://pastebin.com/LKpLNzQq
Config: https://pastebin.com/3D4uM08n
Paper 373
Headsplus 5.1.7

**Comment by Thatsmusic99** [comment] 2018-10-18 14:31
Possibly duplicate of #8 which has been solved. If this isn’t the case let me know.

**Comment by kaimokene** [comment] 2018-10-19 18:56
It seems to be fixed but there seems to be another bug happening ill make a new issue about it.

**Closed** 2018-10-19 20:00 UTC

**Comment by kaimokene** [comment] 2018-10-22 19:41
Apparently the error wasn't fixed. It happened again after restarting server. It seems to error once the server starts. Plugin works fine though.

**Comment by Thatsmusic99** [comment] 2018-10-23 04:09
Then it must be a different error - send that again and I’ll look into it. Thanks for letting me know.

**Comment by Thatsmusic99** [comment] 2018-10-23 17:17
Can't reproduce on paper-366 on version 5.1.8.

**Comment by kaimokene** [comment] 2018-10-24 10:04
It was exactly the same. And very strange it doesnt happen to u. Did u disable craft-heads from config since thats what i have disabled.

**Comment by Thatsmusic99** [comment] 2018-10-24 15:53
It may look the same but it may point me in a different direction. And if possible please send me your configuration files, my main focuses being heads.yml and crafting.yml. 

If you get a report saved in the debug file too, I'd say send me that as well. Because that will have every single piece of information I need to know (e.g configuration, server version) since I'm not getting far at all here.

**Comment by kaimokene** [comment] 2018-10-24 17:21
Okay, ill give u the issue. https://pastebin.com/vrE8p8fn and the configs Heads: https://pastebin.com/TNn0wi9N  Crafting: https://pastebin.com/g6zDT4Ae Sorry for not posting these earlier the reason being is because i dont have access to the console and i would have to communicate with another person to get these.
