### ISSUE TITLE
Problem with head selling

### ISSUE THREAD

**Issue by favorit5503** [Thatsmusic99/HeadsPlus#27] opened 2019-03-20 20:43 UTC
### Short summary of issue
Problem with head selling
### Server version
1.13.2
### HeadsPlus version
6.0.1
### Detailed description (how you found it, what you were doing at the time)
Hi. We found a major bug in the latest version 6.0.1. If you have 5x zombie head. And if you put from this 5 one on your head and try to sell. The plugin will only sell the head on your head the 4 remains in you inventory. But you recieve the price for the 5 head total. I hope you understanded it :D This way a player can farm more money.
### Expected behaviour
Sell all heads and get the proper money
### Actual behaviour
Sells only head on head but gives you money for all of the selled head
### Steps to reproduce
See detailed
### Any last notes?
Thank you

**Comment by Thatsmusic99** [comment] 2019-03-20 20:46
Will try and reproduce tomorrow as mentioned on Spigot.

**Comment by favorit5503** [comment] 2019-03-20 20:59
Thank you. Sry i forgot for a moment that the issues must be on github :D

**Comment by Thatsmusic99** [comment] 2019-03-21 19:48
Fixed in latest version.

**Comment by favorit5503** [comment] 2019-03-25 18:46
Tested but now if we sell 5 heads. One on head 4 in the inventory. The head price is 10 each, It counts in total 60. If you had six heads instead of 5

**Comment by Thatsmusic99** [comment] 2019-03-25 19:04
Will have to sort out later. Am on a break due to schoolwork/mental health.

**Comment by favorit5503** [comment] 2019-03-25 19:05
No problem no need to rush i am just reporting :) Go get better

**Comment by Thatsmusic99** [comment] 2019-03-29 17:35
Should be fixed in v6.0.4-SNAPSHOT-1 in Releases: https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v6.0.4-SNAPSHOT-1

**Comment by Thatsmusic99** [comment] 2019-04-10 14:09
No further word from OP and no mentioning of it being reproduced, so closing this issue.

**Closed** 2019-04-10 14:09 UTC
